#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEstacionaFacil.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EstacionaFacil")]
	public partial class CrudEstacionaFacil : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTB_CLIENTES_CONVENIO(TB_CLIENTES_CONVENIO instance);
    partial void UpdateTB_CLIENTES_CONVENIO(TB_CLIENTES_CONVENIO instance);
    partial void DeleteTB_CLIENTES_CONVENIO(TB_CLIENTES_CONVENIO instance);
    partial void InsertTB_VEICULO(TB_VEICULO instance);
    partial void UpdateTB_VEICULO(TB_VEICULO instance);
    partial void DeleteTB_VEICULO(TB_VEICULO instance);
    partial void InsertTB_CLIENTES_DIARIO(TB_CLIENTES_DIARIO instance);
    partial void UpdateTB_CLIENTES_DIARIO(TB_CLIENTES_DIARIO instance);
    partial void DeleteTB_CLIENTES_DIARIO(TB_CLIENTES_DIARIO instance);
    partial void InsertTB_CONTROLE_VAGA(TB_CONTROLE_VAGA instance);
    partial void UpdateTB_CONTROLE_VAGA(TB_CONTROLE_VAGA instance);
    partial void DeleteTB_CONTROLE_VAGA(TB_CONTROLE_VAGA instance);
    partial void InsertTB_CONVENIO(TB_CONVENIO instance);
    partial void UpdateTB_CONVENIO(TB_CONVENIO instance);
    partial void DeleteTB_CONVENIO(TB_CONVENIO instance);
    partial void InsertTB_FLUXO_CAIXA(TB_FLUXO_CAIXA instance);
    partial void UpdateTB_FLUXO_CAIXA(TB_FLUXO_CAIXA instance);
    partial void DeleteTB_FLUXO_CAIXA(TB_FLUXO_CAIXA instance);
    partial void InsertTB_FLUXO_ENTRADA_SAIDA(TB_FLUXO_ENTRADA_SAIDA instance);
    partial void UpdateTB_FLUXO_ENTRADA_SAIDA(TB_FLUXO_ENTRADA_SAIDA instance);
    partial void DeleteTB_FLUXO_ENTRADA_SAIDA(TB_FLUXO_ENTRADA_SAIDA instance);
    #endregion
		
		public CrudEstacionaFacil() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EstacionaFacil"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CrudEstacionaFacil(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrudEstacionaFacil(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrudEstacionaFacil(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrudEstacionaFacil(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_CLIENTES_CONVENIO> TB_CLIENTES_CONVENIOs
		{
			get
			{
				return this.GetTable<TB_CLIENTES_CONVENIO>();
			}
		}
		
		public System.Data.Linq.Table<TB_VEICULO> TB_VEICULOs
		{
			get
			{
				return this.GetTable<TB_VEICULO>();
			}
		}
		
		public System.Data.Linq.Table<TB_CLIENTES_DIARIO> TB_CLIENTES_DIARIOs
		{
			get
			{
				return this.GetTable<TB_CLIENTES_DIARIO>();
			}
		}
		
		public System.Data.Linq.Table<TB_CONTROLE_VAGA> TB_CONTROLE_VAGAs
		{
			get
			{
				return this.GetTable<TB_CONTROLE_VAGA>();
			}
		}
		
		public System.Data.Linq.Table<TB_CONVENIO> TB_CONVENIOs
		{
			get
			{
				return this.GetTable<TB_CONVENIO>();
			}
		}
		
		public System.Data.Linq.Table<TB_FLUXO_CAIXA> TB_FLUXO_CAIXAs
		{
			get
			{
				return this.GetTable<TB_FLUXO_CAIXA>();
			}
		}
		
		public System.Data.Linq.Table<TB_FLUXO_ENTRADA_SAIDA> TB_FLUXO_ENTRADA_SAIDAs
		{
			get
			{
				return this.GetTable<TB_FLUXO_ENTRADA_SAIDA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CLIENTES_CONVENIO")]
	public partial class TB_CLIENTES_CONVENIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Cliente_Convenio;
		
		private int _ID_Veiculo;
		
		private string _Nome_Cliente_Convenio;
		
		private string _CPF_Cliente_Convenio;
		
		private string _RG_Cliente_Convenio;
		
		private string _Endereco_Cliente_Convenio;
		
		private string _Numero_Cliente_Convenio;
		
		private string _Bairro_Cliente_Convenio;
		
		private string _Cidade_Cliente_Convenio;
		
		private string _Estado_Cliente_Convenio;
		
		private string _Telefone;
		
		private string _Celular;
		
		private string _Email;
		
		private EntitySet<TB_CONTROLE_VAGA> _TB_CONTROLE_VAGAs;
		
		private EntitySet<TB_CONVENIO> _TB_CONVENIOs;
		
		private EntitySet<TB_FLUXO_ENTRADA_SAIDA> _TB_FLUXO_ENTRADA_SAIDAs;
		
		private EntityRef<TB_VEICULO> _TB_VEICULO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Cliente_ConvenioChanging(int value);
    partial void OnID_Cliente_ConvenioChanged();
    partial void OnID_VeiculoChanging(int value);
    partial void OnID_VeiculoChanged();
    partial void OnNome_Cliente_ConvenioChanging(string value);
    partial void OnNome_Cliente_ConvenioChanged();
    partial void OnCPF_Cliente_ConvenioChanging(string value);
    partial void OnCPF_Cliente_ConvenioChanged();
    partial void OnRG_Cliente_ConvenioChanging(string value);
    partial void OnRG_Cliente_ConvenioChanged();
    partial void OnEndereco_Cliente_ConvenioChanging(string value);
    partial void OnEndereco_Cliente_ConvenioChanged();
    partial void OnNumero_Cliente_ConvenioChanging(string value);
    partial void OnNumero_Cliente_ConvenioChanged();
    partial void OnBairro_Cliente_ConvenioChanging(string value);
    partial void OnBairro_Cliente_ConvenioChanged();
    partial void OnCidade_Cliente_ConvenioChanging(string value);
    partial void OnCidade_Cliente_ConvenioChanged();
    partial void OnEstado_Cliente_ConvenioChanging(string value);
    partial void OnEstado_Cliente_ConvenioChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public TB_CLIENTES_CONVENIO()
		{
			this._TB_CONTROLE_VAGAs = new EntitySet<TB_CONTROLE_VAGA>(new Action<TB_CONTROLE_VAGA>(this.attach_TB_CONTROLE_VAGAs), new Action<TB_CONTROLE_VAGA>(this.detach_TB_CONTROLE_VAGAs));
			this._TB_CONVENIOs = new EntitySet<TB_CONVENIO>(new Action<TB_CONVENIO>(this.attach_TB_CONVENIOs), new Action<TB_CONVENIO>(this.detach_TB_CONVENIOs));
			this._TB_FLUXO_ENTRADA_SAIDAs = new EntitySet<TB_FLUXO_ENTRADA_SAIDA>(new Action<TB_FLUXO_ENTRADA_SAIDA>(this.attach_TB_FLUXO_ENTRADA_SAIDAs), new Action<TB_FLUXO_ENTRADA_SAIDA>(this.detach_TB_FLUXO_ENTRADA_SAIDAs));
			this._TB_VEICULO = default(EntityRef<TB_VEICULO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Cliente_Convenio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Cliente_Convenio
		{
			get
			{
				return this._ID_Cliente_Convenio;
			}
			set
			{
				if ((this._ID_Cliente_Convenio != value))
				{
					this.OnID_Cliente_ConvenioChanging(value);
					this.SendPropertyChanging();
					this._ID_Cliente_Convenio = value;
					this.SendPropertyChanged("ID_Cliente_Convenio");
					this.OnID_Cliente_ConvenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Veiculo", DbType="Int NOT NULL")]
		public int ID_Veiculo
		{
			get
			{
				return this._ID_Veiculo;
			}
			set
			{
				if ((this._ID_Veiculo != value))
				{
					if (this._TB_VEICULO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_VeiculoChanging(value);
					this.SendPropertyChanging();
					this._ID_Veiculo = value;
					this.SendPropertyChanged("ID_Veiculo");
					this.OnID_VeiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome_Cliente_Convenio", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string Nome_Cliente_Convenio
		{
			get
			{
				return this._Nome_Cliente_Convenio;
			}
			set
			{
				if ((this._Nome_Cliente_Convenio != value))
				{
					this.OnNome_Cliente_ConvenioChanging(value);
					this.SendPropertyChanging();
					this._Nome_Cliente_Convenio = value;
					this.SendPropertyChanged("Nome_Cliente_Convenio");
					this.OnNome_Cliente_ConvenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF_Cliente_Convenio", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CPF_Cliente_Convenio
		{
			get
			{
				return this._CPF_Cliente_Convenio;
			}
			set
			{
				if ((this._CPF_Cliente_Convenio != value))
				{
					this.OnCPF_Cliente_ConvenioChanging(value);
					this.SendPropertyChanging();
					this._CPF_Cliente_Convenio = value;
					this.SendPropertyChanged("CPF_Cliente_Convenio");
					this.OnCPF_Cliente_ConvenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG_Cliente_Convenio", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string RG_Cliente_Convenio
		{
			get
			{
				return this._RG_Cliente_Convenio;
			}
			set
			{
				if ((this._RG_Cliente_Convenio != value))
				{
					this.OnRG_Cliente_ConvenioChanging(value);
					this.SendPropertyChanging();
					this._RG_Cliente_Convenio = value;
					this.SendPropertyChanged("RG_Cliente_Convenio");
					this.OnRG_Cliente_ConvenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco_Cliente_Convenio", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string Endereco_Cliente_Convenio
		{
			get
			{
				return this._Endereco_Cliente_Convenio;
			}
			set
			{
				if ((this._Endereco_Cliente_Convenio != value))
				{
					this.OnEndereco_Cliente_ConvenioChanging(value);
					this.SendPropertyChanging();
					this._Endereco_Cliente_Convenio = value;
					this.SendPropertyChanged("Endereco_Cliente_Convenio");
					this.OnEndereco_Cliente_ConvenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_Cliente_Convenio", DbType="VarChar(6)")]
		public string Numero_Cliente_Convenio
		{
			get
			{
				return this._Numero_Cliente_Convenio;
			}
			set
			{
				if ((this._Numero_Cliente_Convenio != value))
				{
					this.OnNumero_Cliente_ConvenioChanging(value);
					this.SendPropertyChanging();
					this._Numero_Cliente_Convenio = value;
					this.SendPropertyChanged("Numero_Cliente_Convenio");
					this.OnNumero_Cliente_ConvenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bairro_Cliente_Convenio", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string Bairro_Cliente_Convenio
		{
			get
			{
				return this._Bairro_Cliente_Convenio;
			}
			set
			{
				if ((this._Bairro_Cliente_Convenio != value))
				{
					this.OnBairro_Cliente_ConvenioChanging(value);
					this.SendPropertyChanging();
					this._Bairro_Cliente_Convenio = value;
					this.SendPropertyChanged("Bairro_Cliente_Convenio");
					this.OnBairro_Cliente_ConvenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade_Cliente_Convenio", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string Cidade_Cliente_Convenio
		{
			get
			{
				return this._Cidade_Cliente_Convenio;
			}
			set
			{
				if ((this._Cidade_Cliente_Convenio != value))
				{
					this.OnCidade_Cliente_ConvenioChanging(value);
					this.SendPropertyChanging();
					this._Cidade_Cliente_Convenio = value;
					this.SendPropertyChanged("Cidade_Cliente_Convenio");
					this.OnCidade_Cliente_ConvenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Cliente_Convenio", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Estado_Cliente_Convenio
		{
			get
			{
				return this._Estado_Cliente_Convenio;
			}
			set
			{
				if ((this._Estado_Cliente_Convenio != value))
				{
					this.OnEstado_Cliente_ConvenioChanging(value);
					this.SendPropertyChanging();
					this._Estado_Cliente_Convenio = value;
					this.SendPropertyChanged("Estado_Cliente_Convenio");
					this.OnEstado_Cliente_ConvenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(12)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(12)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(200)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLIENTES_CONVENIO_TB_CONTROLE_VAGA", Storage="_TB_CONTROLE_VAGAs", ThisKey="ID_Cliente_Convenio", OtherKey="ID_Cliente_Convenio")]
		public EntitySet<TB_CONTROLE_VAGA> TB_CONTROLE_VAGAs
		{
			get
			{
				return this._TB_CONTROLE_VAGAs;
			}
			set
			{
				this._TB_CONTROLE_VAGAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLIENTES_CONVENIO_TB_CONVENIO", Storage="_TB_CONVENIOs", ThisKey="ID_Cliente_Convenio", OtherKey="ID_Cliente_Convenio")]
		public EntitySet<TB_CONVENIO> TB_CONVENIOs
		{
			get
			{
				return this._TB_CONVENIOs;
			}
			set
			{
				this._TB_CONVENIOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLIENTES_CONVENIO_TB_FLUXO_ENTRADA_SAIDA", Storage="_TB_FLUXO_ENTRADA_SAIDAs", ThisKey="ID_Cliente_Convenio", OtherKey="ID_Cliente_Convenio")]
		public EntitySet<TB_FLUXO_ENTRADA_SAIDA> TB_FLUXO_ENTRADA_SAIDAs
		{
			get
			{
				return this._TB_FLUXO_ENTRADA_SAIDAs;
			}
			set
			{
				this._TB_FLUXO_ENTRADA_SAIDAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_VEICULO_TB_CLIENTES_CONVENIO", Storage="_TB_VEICULO", ThisKey="ID_Veiculo", OtherKey="ID_Veiculo", IsForeignKey=true)]
		public TB_VEICULO TB_VEICULO
		{
			get
			{
				return this._TB_VEICULO.Entity;
			}
			set
			{
				TB_VEICULO previousValue = this._TB_VEICULO.Entity;
				if (((previousValue != value) 
							|| (this._TB_VEICULO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_VEICULO.Entity = null;
						previousValue.TB_CLIENTES_CONVENIOs.Remove(this);
					}
					this._TB_VEICULO.Entity = value;
					if ((value != null))
					{
						value.TB_CLIENTES_CONVENIOs.Add(this);
						this._ID_Veiculo = value.ID_Veiculo;
					}
					else
					{
						this._ID_Veiculo = default(int);
					}
					this.SendPropertyChanged("TB_VEICULO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_CONTROLE_VAGAs(TB_CONTROLE_VAGA entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLIENTES_CONVENIO = this;
		}
		
		private void detach_TB_CONTROLE_VAGAs(TB_CONTROLE_VAGA entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLIENTES_CONVENIO = null;
		}
		
		private void attach_TB_CONVENIOs(TB_CONVENIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLIENTES_CONVENIO = this;
		}
		
		private void detach_TB_CONVENIOs(TB_CONVENIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLIENTES_CONVENIO = null;
		}
		
		private void attach_TB_FLUXO_ENTRADA_SAIDAs(TB_FLUXO_ENTRADA_SAIDA entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLIENTES_CONVENIO = this;
		}
		
		private void detach_TB_FLUXO_ENTRADA_SAIDAs(TB_FLUXO_ENTRADA_SAIDA entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLIENTES_CONVENIO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_VEICULOS")]
	public partial class TB_VEICULO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Veiculo;
		
		private string _Placa_Veiculo;
		
		private string _Marca_Veiculo;
		
		private string _Cor_Veiculo;
		
		private EntitySet<TB_CLIENTES_CONVENIO> _TB_CLIENTES_CONVENIOs;
		
		private EntitySet<TB_CLIENTES_DIARIO> _TB_CLIENTES_DIARIOs;
		
		private EntitySet<TB_CONTROLE_VAGA> _TB_CONTROLE_VAGAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VeiculoChanging(int value);
    partial void OnID_VeiculoChanged();
    partial void OnPlaca_VeiculoChanging(string value);
    partial void OnPlaca_VeiculoChanged();
    partial void OnMarca_VeiculoChanging(string value);
    partial void OnMarca_VeiculoChanged();
    partial void OnCor_VeiculoChanging(string value);
    partial void OnCor_VeiculoChanged();
    #endregion
		
		public TB_VEICULO()
		{
			this._TB_CLIENTES_CONVENIOs = new EntitySet<TB_CLIENTES_CONVENIO>(new Action<TB_CLIENTES_CONVENIO>(this.attach_TB_CLIENTES_CONVENIOs), new Action<TB_CLIENTES_CONVENIO>(this.detach_TB_CLIENTES_CONVENIOs));
			this._TB_CLIENTES_DIARIOs = new EntitySet<TB_CLIENTES_DIARIO>(new Action<TB_CLIENTES_DIARIO>(this.attach_TB_CLIENTES_DIARIOs), new Action<TB_CLIENTES_DIARIO>(this.detach_TB_CLIENTES_DIARIOs));
			this._TB_CONTROLE_VAGAs = new EntitySet<TB_CONTROLE_VAGA>(new Action<TB_CONTROLE_VAGA>(this.attach_TB_CONTROLE_VAGAs), new Action<TB_CONTROLE_VAGA>(this.detach_TB_CONTROLE_VAGAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Veiculo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Veiculo
		{
			get
			{
				return this._ID_Veiculo;
			}
			set
			{
				if ((this._ID_Veiculo != value))
				{
					this.OnID_VeiculoChanging(value);
					this.SendPropertyChanging();
					this._ID_Veiculo = value;
					this.SendPropertyChanged("ID_Veiculo");
					this.OnID_VeiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Placa_Veiculo", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Placa_Veiculo
		{
			get
			{
				return this._Placa_Veiculo;
			}
			set
			{
				if ((this._Placa_Veiculo != value))
				{
					this.OnPlaca_VeiculoChanging(value);
					this.SendPropertyChanging();
					this._Placa_Veiculo = value;
					this.SendPropertyChanged("Placa_Veiculo");
					this.OnPlaca_VeiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca_Veiculo", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string Marca_Veiculo
		{
			get
			{
				return this._Marca_Veiculo;
			}
			set
			{
				if ((this._Marca_Veiculo != value))
				{
					this.OnMarca_VeiculoChanging(value);
					this.SendPropertyChanging();
					this._Marca_Veiculo = value;
					this.SendPropertyChanged("Marca_Veiculo");
					this.OnMarca_VeiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cor_Veiculo", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Cor_Veiculo
		{
			get
			{
				return this._Cor_Veiculo;
			}
			set
			{
				if ((this._Cor_Veiculo != value))
				{
					this.OnCor_VeiculoChanging(value);
					this.SendPropertyChanging();
					this._Cor_Veiculo = value;
					this.SendPropertyChanged("Cor_Veiculo");
					this.OnCor_VeiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_VEICULO_TB_CLIENTES_CONVENIO", Storage="_TB_CLIENTES_CONVENIOs", ThisKey="ID_Veiculo", OtherKey="ID_Veiculo")]
		public EntitySet<TB_CLIENTES_CONVENIO> TB_CLIENTES_CONVENIOs
		{
			get
			{
				return this._TB_CLIENTES_CONVENIOs;
			}
			set
			{
				this._TB_CLIENTES_CONVENIOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_VEICULO_TB_CLIENTES_DIARIO", Storage="_TB_CLIENTES_DIARIOs", ThisKey="ID_Veiculo", OtherKey="ID_Veiculo")]
		public EntitySet<TB_CLIENTES_DIARIO> TB_CLIENTES_DIARIOs
		{
			get
			{
				return this._TB_CLIENTES_DIARIOs;
			}
			set
			{
				this._TB_CLIENTES_DIARIOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_VEICULO_TB_CONTROLE_VAGA", Storage="_TB_CONTROLE_VAGAs", ThisKey="ID_Veiculo", OtherKey="ID_Veiculo")]
		public EntitySet<TB_CONTROLE_VAGA> TB_CONTROLE_VAGAs
		{
			get
			{
				return this._TB_CONTROLE_VAGAs;
			}
			set
			{
				this._TB_CONTROLE_VAGAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_CLIENTES_CONVENIOs(TB_CLIENTES_CONVENIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_VEICULO = this;
		}
		
		private void detach_TB_CLIENTES_CONVENIOs(TB_CLIENTES_CONVENIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_VEICULO = null;
		}
		
		private void attach_TB_CLIENTES_DIARIOs(TB_CLIENTES_DIARIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_VEICULO = this;
		}
		
		private void detach_TB_CLIENTES_DIARIOs(TB_CLIENTES_DIARIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_VEICULO = null;
		}
		
		private void attach_TB_CONTROLE_VAGAs(TB_CONTROLE_VAGA entity)
		{
			this.SendPropertyChanging();
			entity.TB_VEICULO = this;
		}
		
		private void detach_TB_CONTROLE_VAGAs(TB_CONTROLE_VAGA entity)
		{
			this.SendPropertyChanging();
			entity.TB_VEICULO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CLIENTES_DIARIOS")]
	public partial class TB_CLIENTES_DIARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Clientes_Diarios;
		
		private int _ID_Veiculo;
		
		private string _Nome_Cliente_Diario;
		
		private string _Telefone;
		
		private string _Celular;
		
		private EntitySet<TB_CONTROLE_VAGA> _TB_CONTROLE_VAGAs;
		
		private EntitySet<TB_FLUXO_CAIXA> _TB_FLUXO_CAIXAs;
		
		private EntitySet<TB_FLUXO_ENTRADA_SAIDA> _TB_FLUXO_ENTRADA_SAIDAs;
		
		private EntityRef<TB_VEICULO> _TB_VEICULO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Clientes_DiariosChanging(int value);
    partial void OnID_Clientes_DiariosChanged();
    partial void OnID_VeiculoChanging(int value);
    partial void OnID_VeiculoChanged();
    partial void OnNome_Cliente_DiarioChanging(string value);
    partial void OnNome_Cliente_DiarioChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    #endregion
		
		public TB_CLIENTES_DIARIO()
		{
			this._TB_CONTROLE_VAGAs = new EntitySet<TB_CONTROLE_VAGA>(new Action<TB_CONTROLE_VAGA>(this.attach_TB_CONTROLE_VAGAs), new Action<TB_CONTROLE_VAGA>(this.detach_TB_CONTROLE_VAGAs));
			this._TB_FLUXO_CAIXAs = new EntitySet<TB_FLUXO_CAIXA>(new Action<TB_FLUXO_CAIXA>(this.attach_TB_FLUXO_CAIXAs), new Action<TB_FLUXO_CAIXA>(this.detach_TB_FLUXO_CAIXAs));
			this._TB_FLUXO_ENTRADA_SAIDAs = new EntitySet<TB_FLUXO_ENTRADA_SAIDA>(new Action<TB_FLUXO_ENTRADA_SAIDA>(this.attach_TB_FLUXO_ENTRADA_SAIDAs), new Action<TB_FLUXO_ENTRADA_SAIDA>(this.detach_TB_FLUXO_ENTRADA_SAIDAs));
			this._TB_VEICULO = default(EntityRef<TB_VEICULO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Clientes_Diarios", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Clientes_Diarios
		{
			get
			{
				return this._ID_Clientes_Diarios;
			}
			set
			{
				if ((this._ID_Clientes_Diarios != value))
				{
					this.OnID_Clientes_DiariosChanging(value);
					this.SendPropertyChanging();
					this._ID_Clientes_Diarios = value;
					this.SendPropertyChanged("ID_Clientes_Diarios");
					this.OnID_Clientes_DiariosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Veiculo", DbType="Int NOT NULL")]
		public int ID_Veiculo
		{
			get
			{
				return this._ID_Veiculo;
			}
			set
			{
				if ((this._ID_Veiculo != value))
				{
					if (this._TB_VEICULO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_VeiculoChanging(value);
					this.SendPropertyChanging();
					this._ID_Veiculo = value;
					this.SendPropertyChanged("ID_Veiculo");
					this.OnID_VeiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome_Cliente_Diario", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string Nome_Cliente_Diario
		{
			get
			{
				return this._Nome_Cliente_Diario;
			}
			set
			{
				if ((this._Nome_Cliente_Diario != value))
				{
					this.OnNome_Cliente_DiarioChanging(value);
					this.SendPropertyChanging();
					this._Nome_Cliente_Diario = value;
					this.SendPropertyChanged("Nome_Cliente_Diario");
					this.OnNome_Cliente_DiarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(12)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(12)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLIENTES_DIARIO_TB_CONTROLE_VAGA", Storage="_TB_CONTROLE_VAGAs", ThisKey="ID_Clientes_Diarios", OtherKey="ID_Clientes_Diarios")]
		public EntitySet<TB_CONTROLE_VAGA> TB_CONTROLE_VAGAs
		{
			get
			{
				return this._TB_CONTROLE_VAGAs;
			}
			set
			{
				this._TB_CONTROLE_VAGAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLIENTES_DIARIO_TB_FLUXO_CAIXA", Storage="_TB_FLUXO_CAIXAs", ThisKey="ID_Clientes_Diarios", OtherKey="ID_Clientes_Diarios")]
		public EntitySet<TB_FLUXO_CAIXA> TB_FLUXO_CAIXAs
		{
			get
			{
				return this._TB_FLUXO_CAIXAs;
			}
			set
			{
				this._TB_FLUXO_CAIXAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLIENTES_DIARIO_TB_FLUXO_ENTRADA_SAIDA", Storage="_TB_FLUXO_ENTRADA_SAIDAs", ThisKey="ID_Clientes_Diarios", OtherKey="ID_Clientes_Diarios")]
		public EntitySet<TB_FLUXO_ENTRADA_SAIDA> TB_FLUXO_ENTRADA_SAIDAs
		{
			get
			{
				return this._TB_FLUXO_ENTRADA_SAIDAs;
			}
			set
			{
				this._TB_FLUXO_ENTRADA_SAIDAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_VEICULO_TB_CLIENTES_DIARIO", Storage="_TB_VEICULO", ThisKey="ID_Veiculo", OtherKey="ID_Veiculo", IsForeignKey=true)]
		public TB_VEICULO TB_VEICULO
		{
			get
			{
				return this._TB_VEICULO.Entity;
			}
			set
			{
				TB_VEICULO previousValue = this._TB_VEICULO.Entity;
				if (((previousValue != value) 
							|| (this._TB_VEICULO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_VEICULO.Entity = null;
						previousValue.TB_CLIENTES_DIARIOs.Remove(this);
					}
					this._TB_VEICULO.Entity = value;
					if ((value != null))
					{
						value.TB_CLIENTES_DIARIOs.Add(this);
						this._ID_Veiculo = value.ID_Veiculo;
					}
					else
					{
						this._ID_Veiculo = default(int);
					}
					this.SendPropertyChanged("TB_VEICULO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_CONTROLE_VAGAs(TB_CONTROLE_VAGA entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLIENTES_DIARIO = this;
		}
		
		private void detach_TB_CONTROLE_VAGAs(TB_CONTROLE_VAGA entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLIENTES_DIARIO = null;
		}
		
		private void attach_TB_FLUXO_CAIXAs(TB_FLUXO_CAIXA entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLIENTES_DIARIO = this;
		}
		
		private void detach_TB_FLUXO_CAIXAs(TB_FLUXO_CAIXA entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLIENTES_DIARIO = null;
		}
		
		private void attach_TB_FLUXO_ENTRADA_SAIDAs(TB_FLUXO_ENTRADA_SAIDA entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLIENTES_DIARIO = this;
		}
		
		private void detach_TB_FLUXO_ENTRADA_SAIDAs(TB_FLUXO_ENTRADA_SAIDA entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLIENTES_DIARIO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CONTROLE_VAGAS")]
	public partial class TB_CONTROLE_VAGA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Vagas;
		
		private int _ID_Veiculo;
		
		private int _ID_Clientes_Diarios;
		
		private int _ID_Cliente_Convenio;
		
		private string _Vaga;
		
		private EntityRef<TB_CLIENTES_CONVENIO> _TB_CLIENTES_CONVENIO;
		
		private EntityRef<TB_CLIENTES_DIARIO> _TB_CLIENTES_DIARIO;
		
		private EntityRef<TB_VEICULO> _TB_VEICULO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VagasChanging(int value);
    partial void OnID_VagasChanged();
    partial void OnID_VeiculoChanging(int value);
    partial void OnID_VeiculoChanged();
    partial void OnID_Clientes_DiariosChanging(int value);
    partial void OnID_Clientes_DiariosChanged();
    partial void OnID_Cliente_ConvenioChanging(int value);
    partial void OnID_Cliente_ConvenioChanged();
    partial void OnVagaChanging(string value);
    partial void OnVagaChanged();
    #endregion
		
		public TB_CONTROLE_VAGA()
		{
			this._TB_CLIENTES_CONVENIO = default(EntityRef<TB_CLIENTES_CONVENIO>);
			this._TB_CLIENTES_DIARIO = default(EntityRef<TB_CLIENTES_DIARIO>);
			this._TB_VEICULO = default(EntityRef<TB_VEICULO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Vagas", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Vagas
		{
			get
			{
				return this._ID_Vagas;
			}
			set
			{
				if ((this._ID_Vagas != value))
				{
					this.OnID_VagasChanging(value);
					this.SendPropertyChanging();
					this._ID_Vagas = value;
					this.SendPropertyChanged("ID_Vagas");
					this.OnID_VagasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Veiculo", DbType="Int NOT NULL")]
		public int ID_Veiculo
		{
			get
			{
				return this._ID_Veiculo;
			}
			set
			{
				if ((this._ID_Veiculo != value))
				{
					if (this._TB_VEICULO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_VeiculoChanging(value);
					this.SendPropertyChanging();
					this._ID_Veiculo = value;
					this.SendPropertyChanged("ID_Veiculo");
					this.OnID_VeiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Clientes_Diarios", DbType="Int NOT NULL")]
		public int ID_Clientes_Diarios
		{
			get
			{
				return this._ID_Clientes_Diarios;
			}
			set
			{
				if ((this._ID_Clientes_Diarios != value))
				{
					if (this._TB_CLIENTES_DIARIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_Clientes_DiariosChanging(value);
					this.SendPropertyChanging();
					this._ID_Clientes_Diarios = value;
					this.SendPropertyChanged("ID_Clientes_Diarios");
					this.OnID_Clientes_DiariosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Cliente_Convenio", DbType="Int NOT NULL")]
		public int ID_Cliente_Convenio
		{
			get
			{
				return this._ID_Cliente_Convenio;
			}
			set
			{
				if ((this._ID_Cliente_Convenio != value))
				{
					if (this._TB_CLIENTES_CONVENIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_Cliente_ConvenioChanging(value);
					this.SendPropertyChanging();
					this._ID_Cliente_Convenio = value;
					this.SendPropertyChanged("ID_Cliente_Convenio");
					this.OnID_Cliente_ConvenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vaga", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Vaga
		{
			get
			{
				return this._Vaga;
			}
			set
			{
				if ((this._Vaga != value))
				{
					this.OnVagaChanging(value);
					this.SendPropertyChanging();
					this._Vaga = value;
					this.SendPropertyChanged("Vaga");
					this.OnVagaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLIENTES_CONVENIO_TB_CONTROLE_VAGA", Storage="_TB_CLIENTES_CONVENIO", ThisKey="ID_Cliente_Convenio", OtherKey="ID_Cliente_Convenio", IsForeignKey=true)]
		public TB_CLIENTES_CONVENIO TB_CLIENTES_CONVENIO
		{
			get
			{
				return this._TB_CLIENTES_CONVENIO.Entity;
			}
			set
			{
				TB_CLIENTES_CONVENIO previousValue = this._TB_CLIENTES_CONVENIO.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLIENTES_CONVENIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLIENTES_CONVENIO.Entity = null;
						previousValue.TB_CONTROLE_VAGAs.Remove(this);
					}
					this._TB_CLIENTES_CONVENIO.Entity = value;
					if ((value != null))
					{
						value.TB_CONTROLE_VAGAs.Add(this);
						this._ID_Cliente_Convenio = value.ID_Cliente_Convenio;
					}
					else
					{
						this._ID_Cliente_Convenio = default(int);
					}
					this.SendPropertyChanged("TB_CLIENTES_CONVENIO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLIENTES_DIARIO_TB_CONTROLE_VAGA", Storage="_TB_CLIENTES_DIARIO", ThisKey="ID_Clientes_Diarios", OtherKey="ID_Clientes_Diarios", IsForeignKey=true)]
		public TB_CLIENTES_DIARIO TB_CLIENTES_DIARIO
		{
			get
			{
				return this._TB_CLIENTES_DIARIO.Entity;
			}
			set
			{
				TB_CLIENTES_DIARIO previousValue = this._TB_CLIENTES_DIARIO.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLIENTES_DIARIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLIENTES_DIARIO.Entity = null;
						previousValue.TB_CONTROLE_VAGAs.Remove(this);
					}
					this._TB_CLIENTES_DIARIO.Entity = value;
					if ((value != null))
					{
						value.TB_CONTROLE_VAGAs.Add(this);
						this._ID_Clientes_Diarios = value.ID_Clientes_Diarios;
					}
					else
					{
						this._ID_Clientes_Diarios = default(int);
					}
					this.SendPropertyChanged("TB_CLIENTES_DIARIO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_VEICULO_TB_CONTROLE_VAGA", Storage="_TB_VEICULO", ThisKey="ID_Veiculo", OtherKey="ID_Veiculo", IsForeignKey=true)]
		public TB_VEICULO TB_VEICULO
		{
			get
			{
				return this._TB_VEICULO.Entity;
			}
			set
			{
				TB_VEICULO previousValue = this._TB_VEICULO.Entity;
				if (((previousValue != value) 
							|| (this._TB_VEICULO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_VEICULO.Entity = null;
						previousValue.TB_CONTROLE_VAGAs.Remove(this);
					}
					this._TB_VEICULO.Entity = value;
					if ((value != null))
					{
						value.TB_CONTROLE_VAGAs.Add(this);
						this._ID_Veiculo = value.ID_Veiculo;
					}
					else
					{
						this._ID_Veiculo = default(int);
					}
					this.SendPropertyChanged("TB_VEICULO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CONVENIOS")]
	public partial class TB_CONVENIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Convenio;
		
		private System.Nullable<int> _ID_Cliente_Convenio;
		
		private string _Razao_Social;
		
		private string _CNPJ;
		
		private EntityRef<TB_CLIENTES_CONVENIO> _TB_CLIENTES_CONVENIO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ConvenioChanging(int value);
    partial void OnID_ConvenioChanged();
    partial void OnID_Cliente_ConvenioChanging(System.Nullable<int> value);
    partial void OnID_Cliente_ConvenioChanged();
    partial void OnRazao_SocialChanging(string value);
    partial void OnRazao_SocialChanged();
    partial void OnCNPJChanging(string value);
    partial void OnCNPJChanged();
    #endregion
		
		public TB_CONVENIO()
		{
			this._TB_CLIENTES_CONVENIO = default(EntityRef<TB_CLIENTES_CONVENIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Convenio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Convenio
		{
			get
			{
				return this._ID_Convenio;
			}
			set
			{
				if ((this._ID_Convenio != value))
				{
					this.OnID_ConvenioChanging(value);
					this.SendPropertyChanging();
					this._ID_Convenio = value;
					this.SendPropertyChanged("ID_Convenio");
					this.OnID_ConvenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Cliente_Convenio", DbType="Int")]
		public System.Nullable<int> ID_Cliente_Convenio
		{
			get
			{
				return this._ID_Cliente_Convenio;
			}
			set
			{
				if ((this._ID_Cliente_Convenio != value))
				{
					if (this._TB_CLIENTES_CONVENIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_Cliente_ConvenioChanging(value);
					this.SendPropertyChanging();
					this._ID_Cliente_Convenio = value;
					this.SendPropertyChanged("ID_Cliente_Convenio");
					this.OnID_Cliente_ConvenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Razao_Social", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string Razao_Social
		{
			get
			{
				return this._Razao_Social;
			}
			set
			{
				if ((this._Razao_Social != value))
				{
					this.OnRazao_SocialChanging(value);
					this.SendPropertyChanging();
					this._Razao_Social = value;
					this.SendPropertyChanged("Razao_Social");
					this.OnRazao_SocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNPJ", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string CNPJ
		{
			get
			{
				return this._CNPJ;
			}
			set
			{
				if ((this._CNPJ != value))
				{
					this.OnCNPJChanging(value);
					this.SendPropertyChanging();
					this._CNPJ = value;
					this.SendPropertyChanged("CNPJ");
					this.OnCNPJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLIENTES_CONVENIO_TB_CONVENIO", Storage="_TB_CLIENTES_CONVENIO", ThisKey="ID_Cliente_Convenio", OtherKey="ID_Cliente_Convenio", IsForeignKey=true)]
		public TB_CLIENTES_CONVENIO TB_CLIENTES_CONVENIO
		{
			get
			{
				return this._TB_CLIENTES_CONVENIO.Entity;
			}
			set
			{
				TB_CLIENTES_CONVENIO previousValue = this._TB_CLIENTES_CONVENIO.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLIENTES_CONVENIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLIENTES_CONVENIO.Entity = null;
						previousValue.TB_CONVENIOs.Remove(this);
					}
					this._TB_CLIENTES_CONVENIO.Entity = value;
					if ((value != null))
					{
						value.TB_CONVENIOs.Add(this);
						this._ID_Cliente_Convenio = value.ID_Cliente_Convenio;
					}
					else
					{
						this._ID_Cliente_Convenio = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_CLIENTES_CONVENIO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_FLUXO_CAIXA")]
	public partial class TB_FLUXO_CAIXA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Fluxo_Caixa;
		
		private int _ID_Clientes_Diarios;
		
		private decimal _Valor;
		
		private EntitySet<TB_FLUXO_ENTRADA_SAIDA> _TB_FLUXO_ENTRADA_SAIDAs;
		
		private EntityRef<TB_CLIENTES_DIARIO> _TB_CLIENTES_DIARIO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Fluxo_CaixaChanging(int value);
    partial void OnID_Fluxo_CaixaChanged();
    partial void OnID_Clientes_DiariosChanging(int value);
    partial void OnID_Clientes_DiariosChanged();
    partial void OnValorChanging(decimal value);
    partial void OnValorChanged();
    #endregion
		
		public TB_FLUXO_CAIXA()
		{
			this._TB_FLUXO_ENTRADA_SAIDAs = new EntitySet<TB_FLUXO_ENTRADA_SAIDA>(new Action<TB_FLUXO_ENTRADA_SAIDA>(this.attach_TB_FLUXO_ENTRADA_SAIDAs), new Action<TB_FLUXO_ENTRADA_SAIDA>(this.detach_TB_FLUXO_ENTRADA_SAIDAs));
			this._TB_CLIENTES_DIARIO = default(EntityRef<TB_CLIENTES_DIARIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Fluxo_Caixa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Fluxo_Caixa
		{
			get
			{
				return this._ID_Fluxo_Caixa;
			}
			set
			{
				if ((this._ID_Fluxo_Caixa != value))
				{
					this.OnID_Fluxo_CaixaChanging(value);
					this.SendPropertyChanging();
					this._ID_Fluxo_Caixa = value;
					this.SendPropertyChanged("ID_Fluxo_Caixa");
					this.OnID_Fluxo_CaixaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Clientes_Diarios", DbType="Int NOT NULL")]
		public int ID_Clientes_Diarios
		{
			get
			{
				return this._ID_Clientes_Diarios;
			}
			set
			{
				if ((this._ID_Clientes_Diarios != value))
				{
					if (this._TB_CLIENTES_DIARIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_Clientes_DiariosChanging(value);
					this.SendPropertyChanging();
					this._ID_Clientes_Diarios = value;
					this.SendPropertyChanged("ID_Clientes_Diarios");
					this.OnID_Clientes_DiariosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Money NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_FLUXO_CAIXA_TB_FLUXO_ENTRADA_SAIDA", Storage="_TB_FLUXO_ENTRADA_SAIDAs", ThisKey="ID_Fluxo_Caixa", OtherKey="ID_Fluxo_Caixa")]
		public EntitySet<TB_FLUXO_ENTRADA_SAIDA> TB_FLUXO_ENTRADA_SAIDAs
		{
			get
			{
				return this._TB_FLUXO_ENTRADA_SAIDAs;
			}
			set
			{
				this._TB_FLUXO_ENTRADA_SAIDAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLIENTES_DIARIO_TB_FLUXO_CAIXA", Storage="_TB_CLIENTES_DIARIO", ThisKey="ID_Clientes_Diarios", OtherKey="ID_Clientes_Diarios", IsForeignKey=true)]
		public TB_CLIENTES_DIARIO TB_CLIENTES_DIARIO
		{
			get
			{
				return this._TB_CLIENTES_DIARIO.Entity;
			}
			set
			{
				TB_CLIENTES_DIARIO previousValue = this._TB_CLIENTES_DIARIO.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLIENTES_DIARIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLIENTES_DIARIO.Entity = null;
						previousValue.TB_FLUXO_CAIXAs.Remove(this);
					}
					this._TB_CLIENTES_DIARIO.Entity = value;
					if ((value != null))
					{
						value.TB_FLUXO_CAIXAs.Add(this);
						this._ID_Clientes_Diarios = value.ID_Clientes_Diarios;
					}
					else
					{
						this._ID_Clientes_Diarios = default(int);
					}
					this.SendPropertyChanged("TB_CLIENTES_DIARIO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_FLUXO_ENTRADA_SAIDAs(TB_FLUXO_ENTRADA_SAIDA entity)
		{
			this.SendPropertyChanging();
			entity.TB_FLUXO_CAIXA = this;
		}
		
		private void detach_TB_FLUXO_ENTRADA_SAIDAs(TB_FLUXO_ENTRADA_SAIDA entity)
		{
			this.SendPropertyChanging();
			entity.TB_FLUXO_CAIXA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_FLUXO_ENTRADA_SAIDA")]
	public partial class TB_FLUXO_ENTRADA_SAIDA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Fluxo_E_S;
		
		private int _ID_Cliente_Convenio;
		
		private int _ID_Clientes_Diarios;
		
		private int _ID_Fluxo_Caixa;
		
		private System.TimeSpan _Hora_Entrada;
		
		private System.TimeSpan _Hora_Saida;
		
		private EntityRef<TB_CLIENTES_CONVENIO> _TB_CLIENTES_CONVENIO;
		
		private EntityRef<TB_CLIENTES_DIARIO> _TB_CLIENTES_DIARIO;
		
		private EntityRef<TB_FLUXO_CAIXA> _TB_FLUXO_CAIXA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Fluxo_E_SChanging(int value);
    partial void OnID_Fluxo_E_SChanged();
    partial void OnID_Cliente_ConvenioChanging(int value);
    partial void OnID_Cliente_ConvenioChanged();
    partial void OnID_Clientes_DiariosChanging(int value);
    partial void OnID_Clientes_DiariosChanged();
    partial void OnID_Fluxo_CaixaChanging(int value);
    partial void OnID_Fluxo_CaixaChanged();
    partial void OnHora_EntradaChanging(System.TimeSpan value);
    partial void OnHora_EntradaChanged();
    partial void OnHora_SaidaChanging(System.TimeSpan value);
    partial void OnHora_SaidaChanged();
    #endregion
		
		public TB_FLUXO_ENTRADA_SAIDA()
		{
			this._TB_CLIENTES_CONVENIO = default(EntityRef<TB_CLIENTES_CONVENIO>);
			this._TB_CLIENTES_DIARIO = default(EntityRef<TB_CLIENTES_DIARIO>);
			this._TB_FLUXO_CAIXA = default(EntityRef<TB_FLUXO_CAIXA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Fluxo_E_S", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Fluxo_E_S
		{
			get
			{
				return this._ID_Fluxo_E_S;
			}
			set
			{
				if ((this._ID_Fluxo_E_S != value))
				{
					this.OnID_Fluxo_E_SChanging(value);
					this.SendPropertyChanging();
					this._ID_Fluxo_E_S = value;
					this.SendPropertyChanged("ID_Fluxo_E_S");
					this.OnID_Fluxo_E_SChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Cliente_Convenio", DbType="Int NOT NULL")]
		public int ID_Cliente_Convenio
		{
			get
			{
				return this._ID_Cliente_Convenio;
			}
			set
			{
				if ((this._ID_Cliente_Convenio != value))
				{
					if (this._TB_CLIENTES_CONVENIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_Cliente_ConvenioChanging(value);
					this.SendPropertyChanging();
					this._ID_Cliente_Convenio = value;
					this.SendPropertyChanged("ID_Cliente_Convenio");
					this.OnID_Cliente_ConvenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Clientes_Diarios", DbType="Int NOT NULL")]
		public int ID_Clientes_Diarios
		{
			get
			{
				return this._ID_Clientes_Diarios;
			}
			set
			{
				if ((this._ID_Clientes_Diarios != value))
				{
					if (this._TB_CLIENTES_DIARIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_Clientes_DiariosChanging(value);
					this.SendPropertyChanging();
					this._ID_Clientes_Diarios = value;
					this.SendPropertyChanged("ID_Clientes_Diarios");
					this.OnID_Clientes_DiariosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Fluxo_Caixa", DbType="Int NOT NULL")]
		public int ID_Fluxo_Caixa
		{
			get
			{
				return this._ID_Fluxo_Caixa;
			}
			set
			{
				if ((this._ID_Fluxo_Caixa != value))
				{
					if (this._TB_FLUXO_CAIXA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_Fluxo_CaixaChanging(value);
					this.SendPropertyChanging();
					this._ID_Fluxo_Caixa = value;
					this.SendPropertyChanged("ID_Fluxo_Caixa");
					this.OnID_Fluxo_CaixaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora_Entrada", DbType="Time NOT NULL")]
		public System.TimeSpan Hora_Entrada
		{
			get
			{
				return this._Hora_Entrada;
			}
			set
			{
				if ((this._Hora_Entrada != value))
				{
					this.OnHora_EntradaChanging(value);
					this.SendPropertyChanging();
					this._Hora_Entrada = value;
					this.SendPropertyChanged("Hora_Entrada");
					this.OnHora_EntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora_Saida", DbType="Time NOT NULL")]
		public System.TimeSpan Hora_Saida
		{
			get
			{
				return this._Hora_Saida;
			}
			set
			{
				if ((this._Hora_Saida != value))
				{
					this.OnHora_SaidaChanging(value);
					this.SendPropertyChanging();
					this._Hora_Saida = value;
					this.SendPropertyChanged("Hora_Saida");
					this.OnHora_SaidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLIENTES_CONVENIO_TB_FLUXO_ENTRADA_SAIDA", Storage="_TB_CLIENTES_CONVENIO", ThisKey="ID_Cliente_Convenio", OtherKey="ID_Cliente_Convenio", IsForeignKey=true)]
		public TB_CLIENTES_CONVENIO TB_CLIENTES_CONVENIO
		{
			get
			{
				return this._TB_CLIENTES_CONVENIO.Entity;
			}
			set
			{
				TB_CLIENTES_CONVENIO previousValue = this._TB_CLIENTES_CONVENIO.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLIENTES_CONVENIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLIENTES_CONVENIO.Entity = null;
						previousValue.TB_FLUXO_ENTRADA_SAIDAs.Remove(this);
					}
					this._TB_CLIENTES_CONVENIO.Entity = value;
					if ((value != null))
					{
						value.TB_FLUXO_ENTRADA_SAIDAs.Add(this);
						this._ID_Cliente_Convenio = value.ID_Cliente_Convenio;
					}
					else
					{
						this._ID_Cliente_Convenio = default(int);
					}
					this.SendPropertyChanged("TB_CLIENTES_CONVENIO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLIENTES_DIARIO_TB_FLUXO_ENTRADA_SAIDA", Storage="_TB_CLIENTES_DIARIO", ThisKey="ID_Clientes_Diarios", OtherKey="ID_Clientes_Diarios", IsForeignKey=true)]
		public TB_CLIENTES_DIARIO TB_CLIENTES_DIARIO
		{
			get
			{
				return this._TB_CLIENTES_DIARIO.Entity;
			}
			set
			{
				TB_CLIENTES_DIARIO previousValue = this._TB_CLIENTES_DIARIO.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLIENTES_DIARIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLIENTES_DIARIO.Entity = null;
						previousValue.TB_FLUXO_ENTRADA_SAIDAs.Remove(this);
					}
					this._TB_CLIENTES_DIARIO.Entity = value;
					if ((value != null))
					{
						value.TB_FLUXO_ENTRADA_SAIDAs.Add(this);
						this._ID_Clientes_Diarios = value.ID_Clientes_Diarios;
					}
					else
					{
						this._ID_Clientes_Diarios = default(int);
					}
					this.SendPropertyChanged("TB_CLIENTES_DIARIO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_FLUXO_CAIXA_TB_FLUXO_ENTRADA_SAIDA", Storage="_TB_FLUXO_CAIXA", ThisKey="ID_Fluxo_Caixa", OtherKey="ID_Fluxo_Caixa", IsForeignKey=true)]
		public TB_FLUXO_CAIXA TB_FLUXO_CAIXA
		{
			get
			{
				return this._TB_FLUXO_CAIXA.Entity;
			}
			set
			{
				TB_FLUXO_CAIXA previousValue = this._TB_FLUXO_CAIXA.Entity;
				if (((previousValue != value) 
							|| (this._TB_FLUXO_CAIXA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_FLUXO_CAIXA.Entity = null;
						previousValue.TB_FLUXO_ENTRADA_SAIDAs.Remove(this);
					}
					this._TB_FLUXO_CAIXA.Entity = value;
					if ((value != null))
					{
						value.TB_FLUXO_ENTRADA_SAIDAs.Add(this);
						this._ID_Fluxo_Caixa = value.ID_Fluxo_Caixa;
					}
					else
					{
						this._ID_Fluxo_Caixa = default(int);
					}
					this.SendPropertyChanged("TB_FLUXO_CAIXA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
